site_name: LLM teaching
site_url: https://llmteaching.com

theme:
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - navigation.right
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs
  icon:
    tag:
      context: fontawesome/brands/html5
      role: fontawesome/brands/js
      example:  fontawesome/brands/css3
      scope:  fontawesome/brands/css3
      task:  fontawesome/brands/css3
      format:  fontawesome/brands/css3

nav:
  - "Home": index.md
  - Learners:
    - "About LLMs": llms.md
    - "Ethics": ethics.md
    - "Prompt engineering": prompt_engineering.md
    - "Use cases": usecases.md
    - "Other resources": resources.md
  - Teachers:
    - "Competencies": competencies.md
    - "Activities": activities.md
  - Researchers:
    - "Writing": writing.md
    - "Literature search": literature_search.md
    

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  tags:
    Context: context
    Role: role
    Examples: examples
    Scope: scope
    Task: task
    "Output Format": format

plugins:
  - search
  - tags:
      tags_file: activities.md

copyright: Copyright &copy; 2024 Vidar Skogvoll