site_name: Learning, teaching and doing research with large language models
site_url: https://llmteaching.com

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'light green'
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - navigation.right
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs
  icon:
    tag:
      context: fontawesome/brands/html5
      role: fontawesome/brands/js
      example:  fontawesome/brands/css3
      scope:  fontawesome/brands/css3
      task:  fontawesome/brands/css3
      format:  fontawesome/brands/css3

nav:
  - Overview: 
    - "Home": index.md
    - "About LLMs": llms.md
    - "Prompt engineering": prompt_engineering.md
    - "Ethics": ethics.md
  - Learners: 
    - "Home": learners/index.md
  - Teachers: 
    - "Home": 'teachers/index.md'
    - "Competencies": teachers/competencies.md
    - "Activities": teachers/activities.md
  - Researchers: researchers/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  tags:
    Context: context
    Role: role
    Examples: examples
    Scope: scope
    Task: task
    "Output Format": format

plugins:
  - search
  - tags:
      tags_file: teachers/activities.md
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: nb
          name: Norsk
          build: true
          nav_translations:
            Home: Hjem
            "About LLMs": Om språkmodeller
            "Prompt engineering": Utforming av ledetekster
            Overview: Oversikt
            Learners: Lærende
            Teachers: Lærere
            Researchers: Forskere
            Activities: Aktiviteter

copyright: Copyright &copy; 2024 Vidar Skogvoll