site_name: LLM teaching

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'light green'
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - navigation.right
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false

copyright: Copyright &copy; 2024 Vidar Skogvoll