name: Build MkDocs Site

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install mkdocs-material  # Install MkDocs and Material theme

    - name: Build MkDocs site
      run: mkdocs build